### ISSUE TITLE
Nuke command cooldown

### ISSUE THREAD

**Issue by AngelOnFira** [Developer-X-0001/Cleaner-8788#1]
I couldn't find a working link to the support server, and I can't reach out to you on Discord, so I'll put my request here :)

I love the `nuke` command, it's super helpful on a server I'm using to develop a Discord bot. My bot makes a ton of roles/channels/categories while running its tests, and so nuking once in a while is a great way to start fresh without the need to reinvite the bot or anything.

However, there appears to be a 15-day cooldown that I can't override myself. This isn't so great depending on how much work I do on the bot.

I assume this is in place to reduce the number of hits to the Discord API your bot makes and reduce your own cooldowns, but might it be possible to reduce this cooldown?

**Comment by Developer-X-0001** [comment]
> 

Hello!
Very sorry to hear that from you, but we have to keep our bot from getting ratelimited. I 've applied this cooldown because this command was being heavily used and bot was getting ratelimited. Since, you are working with a bot to test out things. Kindly send me your **Server ID** where you need to re-use nuke command again and again via /suggestion or /report command. I will whitelist that server from cooldown. 😉

Regards,
Developer X
